services:
  web:
    build: .
    environment:
      - DATABASE_URL=mysql://whatsbar_dba:123456@10.200.0.20:3306/whatsbar5
      - JWT_SECRET=supersecretkey
      - PORT=8000
    ports:
     - "8000:8000"
